/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect, useRef } from 'react';
import {
  Sparkles,
  Zap,
  Users,
  Shield,
  BookOpen,
  Play,
  Square,
  CheckCircle2,
  AlertTriangle,
  RefreshCw,
  FileCheck2,
  ChevronDown,
  ChevronUp,
  Target,
  ArrowRight,
  Database,
  Terminal,
  Activity,
  Check,
  Award
} from 'lucide-react';
import { useRuntime } from '../core/RuntimeContext';

interface DeliberationTurn {
  id: string;
  speakerRole: 'Architect' | 'Auditor' | 'Engineer' | 'Referee' | 'User';
  speakerName: string;
  avatarColor: string;
  message: string;
  keyTakeaway?: string;
  timestamp: string;
}

export default function DecisionStudio() {
  const { addLog, updateCanonicalIntent } = useRuntime();

  // Selected Objective / Topic
  const [projectTopic, setProjectTopic] = useState<string>('Build an offline-first mobile inspection app with instant sync and PDF reporting');
  
  // Deliberation Ladder Level (1, 2, or 3)
  const [ladderLevel, setLadderLevel] = useState<1 | 2 | 3>(3);
  
  // Completion Strategy
  const [completionStrategy, setCompletionStrategy] = useState<'CONSENSUS' | 'IMPROVEMENT' | 'MANUAL'>('CONSENSUS');

  // Role Mappings (Interchangeable AI Models assigned to specific expert roles)
  const [roles, setRoles] = useState({
    Architect: { name: 'Lead Architect', model: 'Claude 3.5 Sonnet', desc: 'System topology & data flow models' },
    Auditor: { name: 'Security Auditor', model: 'Gemini 1.5 Pro', desc: 'RLS controls, encryption & sandbox boundaries' },
    Engineer: { name: 'Performance Specialist', model: 'GPT-4o', desc: 'UI frames, IndexedDB batching & memory overhead' },
    Referee: { name: 'Foundation Referee', model: 'Gemini 1.5 Flash', desc: 'ArgOS constitution & ADR alignment guard' }
  });

  // State
  const [isRunning, setIsRunning] = useState<boolean>(false);
  const [turns, setTurns] = useState<DeliberationTurn[]>([]);
  const [isCompleted, setIsCompleted] = useState<boolean>(false);
  const [adopted, setAdopted] = useState<boolean>(false);
  const [showRawTranscript, setShowRawTranscript] = useState<boolean>(false);
  const [userInput, setUserInput] = useState<string>('');

  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    scrollRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [turns, isRunning]);

  // Handle Escalations or Remote triggers
  useEffect(() => {
    const handleSwitchEvent = (e: Event) => {
      const customEvent = e as CustomEvent;
      if (customEvent.detail?.mode === 'COLLABORATIVE') {
        setLadderLevel(2);
        handleStartDeliberationWithLevel(2);
      } else if (customEvent.detail?.mode === 'AUTONOMOUS') {
        setLadderLevel(3);
        handleStartDeliberationWithLevel(3);
      }
    };
    window.addEventListener('SWITCH_DELIBERATION_MODE', handleSwitchEvent);
    return () => window.removeEventListener('SWITCH_DELIBERATION_MODE', handleSwitchEvent);
  }, [projectTopic]);

  const handleStartDeliberationWithLevel = (levelToRun: 1 | 2 | 3) => {
    setTurns([]);
    setIsCompleted(false);
    setAdopted(false);
    setShowRawTranscript(false);
    setIsRunning(true);

    addLog(`Decision Studio: Commencing Ladder Level ${levelToRun} Deliberation`, 'INFO', 'SPINE');

    if (levelToRun === 1) {
      // Level 1: Quick Answer (Direct Response by Lead Architect)
      setTimeout(() => {
        const turn1: DeliberationTurn = {
          id: `lvl1-${Date.now()}`,
          speakerRole: 'Architect',
          speakerName: roles.Architect.name,
          avatarColor: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
          message: `Direct Strategy for "${projectTopic}": Implement client-side IndexedDB local cache. Use dynamic synchronization queues with basic fallback handlers for network disconnects.`,
          keyTakeaway: 'Quick Action: Direct implementation strategy compiled.',
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
        };
        setTurns([turn1]);
        setIsRunning(false);
        setIsCompleted(true);
        addLog(`Quick Answer generated by ${roles.Architect.model}.`, 'SUCCESS', 'SPINE');
      }, 1000);
      return;
    }

    // Level 2 or 3: Interactive / Autonomous Deliberation Sequence
    let currentStep = 0;
    const interval = setInterval(() => {
      currentStep++;

      let newTurn: DeliberationTurn;
      if (currentStep === 1) {
        newTurn = {
          id: `step-1-${Date.now()}`,
          speakerRole: 'Architect',
          speakerName: roles.Architect.name,
          avatarColor: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
          message: `I propose an Event-Sourced client architecture for "${projectTopic}". By capturing user transactions as an immutable local event log, we ensure zero UI latency. We write directly to IndexedDB first, then replicate asynchronously.`,
          keyTakeaway: 'Core Concept: Immutable event log + direct IndexedDB caching.',
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
        };
      } else if (currentStep === 2) {
        newTurn = {
          id: `step-2-${Date.now()}`,
          speakerRole: 'Auditor',
          speakerName: roles.Auditor.name,
          avatarColor: 'text-blue-400 bg-blue-500/10 border-blue-500/30',
          message: `The client event-sourced log is clean, but we must mitigate storage eviction boundaries in prolonged offline states. I mandate adding a high-performance vector log compactor to restrict maximum payload limits to 10MB. We must also secure cross-tenant replication with SHA-256 batch cryptographic tokens.`,
          keyTakeaway: 'Security Mandate: SHA-256 batch tokens + client storage log compaction.',
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
        };
      } else if (currentStep === 3) {
        newTurn = {
          id: `step-3-${Date.now()}`,
          speakerRole: 'Engineer',
          speakerName: roles.Engineer.name,
          avatarColor: 'text-rose-400 bg-rose-500/10 border-rose-500/30',
          message: `To keep the main UI thread at a responsive 60 FPS while compiling offline reports, let's execute the entire PDF rendering queue inside background WebWorkers. This separates high-computation document layout completely from user gestures.`,
          keyTakeaway: 'Performance Strategy: Offload PDF rendering to multi-threaded WebWorkers.',
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
        };
      } else if (currentStep === 4 && levelToRun === 3) {
        // Only Level 3 gets the Foundation Referee check
        newTurn = {
          id: `step-4-${Date.now()}`,
          speakerRole: 'Referee',
          speakerName: roles.Referee.name,
          avatarColor: 'text-[#FFD700] bg-[#FFD700]/10 border-[#FFD700]/30',
          message: `[Foundation Verification]: This dual-expert blueprint is fully aligned with the ArgOS Constitution. Zero drift detected. The design satisfies Mandate #4 (Zero-Drift Security) and Mandate #7 (Performance Thread Isolation). Consensus achieved.`,
          keyTakeaway: 'Referee Audit: HIGH alignment, LOW risk, Consensus ACHIEVED.',
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
        };
      } else {
        // Finalize
        clearInterval(interval);
        setIsRunning(false);
        setIsCompleted(true);
        addLog(`Decision Studio: Deliberation consensus finalized. Visualizing artifacts.`, 'SUCCESS', 'SPINE');
        return;
      }

      setTurns(prev => [...prev, newTurn]);
    }, 1500);
  };

  const handleStartDeliberation = () => {
    handleStartDeliberationWithLevel(ladderLevel);
  };

  const handleStopDeliberation = () => {
    setIsRunning(false);
    setIsCompleted(true);
    addLog('User terminated active deliberation sequence.', 'INFO', 'SPINE');
  };

  const handleSendSteeringInput = (e: React.FormEvent) => {
    e.preventDefault();
    if (!userInput.trim()) return;

    const userTurn: DeliberationTurn = {
      id: `user-${Date.now()}`,
      speakerRole: 'User',
      speakerName: 'Operator Steering',
      avatarColor: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
      message: `[Steering Command]: ${userInput}`,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })
    };

    setTurns(prev => [...prev, userTurn]);
    setUserInput('');
    addLog(`Injected manual operator steering direction into Decision Studio.`, 'INFO', 'SPINE');
  };

  const handleAdoptPlan = () => {
    updateCanonicalIntent(
      `[Decision Studio Refined Blueprint]: ${projectTopic}\n\nConsensus Specifications:\n1. Client-Side Event Sourcing with IndexedDB & Log Compactor\n2. Background WebWorker rendering for 60 FPS performance\n3. PostgreSQL Row-Level Security (RLS) with cryptographic SHA-256 sync tokens\n4. Audited and verified by the Foundation Referee against the ArgOS Constitution`,
      ['Offline-First DB', 'WebWorker Rendering', 'PostgreSQL RLS', 'SHA-256 Sync']
    );
    setAdopted(true);
    addLog('Saved deliberation decision & artifacts to Knowledge Vault.', 'SUCCESS', 'GOVERNOR');
  };

  return (
    <div className="bg-[#080808] border border-[#222] rounded-2xl p-5 space-y-6 font-mono text-xs shadow-2xl">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-[#1b1b1b] pb-4 gap-3">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-amber-500/10 border border-amber-500/30 flex items-center justify-center text-amber-400">
            <Award className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-white font-black uppercase text-sm tracking-wider">Decision Studio</h3>
              <span className="text-[8px] bg-amber-500/10 text-amber-400 border border-amber-500/20 px-2 py-0.5 rounded font-black uppercase">
                Expert Roles
              </span>
            </div>
            <p className="text-[10px] text-gray-400 font-sans mt-0.5">
              Refining user ideas into durable engineering decisions and verified institutional artifacts
            </p>
          </div>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-2 shrink-0">
          {!isRunning ? (
            <button
              onClick={handleStartDeliberation}
              className="bg-[#FFD700] hover:bg-[#FFD700]/90 text-black font-black px-4 py-2 rounded-xl transition flex items-center gap-1.5 cursor-pointer uppercase text-xs shadow-lg"
            >
              <Play className="w-3.5 h-3.5 fill-black" />
              <span>Convene Deliberation</span>
            </button>
          ) : (
            <button
              onClick={handleStopDeliberation}
              className="bg-rose-500 hover:bg-rose-600 text-white font-bold px-4 py-2 rounded-xl transition flex items-center gap-1.5 cursor-pointer uppercase text-xs"
            >
              <Square className="w-3.5 h-3.5 fill-white" />
              <span>Conclude Session</span>
            </button>
          )}
        </div>
      </div>

      {/* THE ARG DECISION LADDER PROGRESSION */}
      <div className="space-y-2">
        <span className="text-[9.5px] text-gray-400 uppercase font-bold block">The Decision Ladder</span>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {[
            {
              id: 1,
              title: '1. Quick Answer',
              sub: 'Fast Execution',
              desc: 'Primary consultant AI outlines a baseline plan. Fast and immediate.'
            },
            {
              id: 2,
              title: '2. Improve Answer',
              sub: 'Interactive Steering',
              desc: 'Architect & Auditor join. You inject custom requirements in real-time.'
            },
            {
              id: 3,
              title: '3. Architectural Review',
              sub: 'Foundation Referee',
              desc: 'Autonomous multi-expert audit. Verifies Constitution alignment & produces artifacts.'
            }
          ].map((level) => {
            const isSelected = ladderLevel === level.id;
            return (
              <button
                key={level.id}
                type="button"
                onClick={() => {
                  if (!isRunning) setLadderLevel(level.id as any);
                }}
                disabled={isRunning}
                className={`p-3.5 rounded-xl border text-left transition cursor-pointer flex flex-col justify-between space-y-1.5 relative overflow-hidden ${
                  isSelected
                    ? 'bg-[#121212] border-[#FFD700]/60 text-white shadow-xl'
                    : 'bg-[#0d0d0d] hover:bg-[#111] border-[#1e1e1e] text-gray-500'
                }`}
              >
                {isSelected && (
                  <div className="absolute top-0 right-0 w-1.5 h-full bg-[#FFD700]" />
                )}
                <div className="flex items-center justify-between">
                  <span className={`font-bold text-xs ${isSelected ? 'text-[#FFD700]' : 'text-white'}`}>
                    {level.title}
                  </span>
                  <span className="text-[8px] bg-white/5 border border-white/10 px-1.5 py-0.2 rounded font-mono">
                    {level.sub}
                  </span>
                </div>
                <p className="text-[10px] font-sans text-gray-400 leading-snug">
                  {level.desc}
                </p>
              </button>
            );
          })}
        </div>
      </div>

      {/* Setup Config Bar */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 bg-[#111] border border-[#222] p-4 rounded-xl">
        
        {/* Objective Input */}
        <div className="lg:col-span-6 space-y-1.5">
          <label className="text-[9.5px] text-gray-400 uppercase font-bold block flex items-center gap-1.5">
            <Target className="w-3.5 h-3.5 text-[#FFD700]" />
            <span>Deliberation Objective / Topic</span>
          </label>
          <input
            type="text"
            value={projectTopic}
            onChange={(e) => setProjectTopic(e.target.value)}
            disabled={isRunning}
            placeholder="Describe the architectural challenge to resolve..."
            className="w-full bg-[#080808] border border-[#2a2a2a] focus:border-[#FFD700] rounded-lg px-3 py-2 text-xs text-white placeholder-gray-600 outline-none font-sans"
          />
        </div>

        {/* Completion Strategy */}
        <div className="lg:col-span-6 space-y-1.5">
          <label className="text-[9.5px] text-gray-400 uppercase font-bold block">
            Completion Strategy
          </label>
          <div className="grid grid-cols-3 gap-2">
            {[
              { id: 'CONSENSUS', label: 'Consensus', desc: 'Stop on referee sign-off' },
              { id: 'IMPROVEMENT', label: 'Improvement', desc: 'Stop after 1st major pass' },
              { id: 'MANUAL', label: 'Manual Stop', desc: 'Keep going until user stops' }
            ].map((strategy) => (
              <button
                key={strategy.id}
                type="button"
                onClick={() => setCompletionStrategy(strategy.id as any)}
                disabled={isRunning}
                className={`p-2 rounded-lg border text-left transition cursor-pointer flex flex-col justify-between ${
                  completionStrategy === strategy.id
                    ? 'bg-[#FFD700]/10 border-[#FFD700] text-white'
                    : 'bg-[#0a0a0a] border-[#222] text-gray-400 hover:border-gray-500'
                }`}
              >
                <span className="font-bold text-[9px] uppercase tracking-wider">{strategy.label}</span>
                <span className="text-[8px] font-sans text-gray-500 leading-none">{strategy.desc}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Assigned Expertise Roles Map (Invisible Brand Selectors) */}
        <div className="lg:col-span-12 border-t border-[#1e1e1e] pt-3.5">
          <div className="flex items-center justify-between mb-2">
            <span className="text-[9.5px] text-gray-400 uppercase font-bold">Convened Expertise Roles</span>
            <span className="text-[8.5px] text-gray-500">Models are auto-allocated for stability</span>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
            {[
              { role: 'Architect', detail: roles.Architect, color: 'border-amber-500/20 text-amber-400' },
              { role: 'Auditor', detail: roles.Auditor, color: 'border-blue-500/20 text-blue-400' },
              { role: 'Engineer', detail: roles.Engineer, color: 'border-rose-500/20 text-rose-400' },
              { role: 'Referee', detail: roles.Referee, color: 'border-[#FFD700]/20 text-[#FFD700]' }
            ].map((expert) => (
              <div
                key={expert.role}
                className={`bg-[#0a0a0a] border ${expert.color} p-2.5 rounded-xl flex flex-col justify-between space-y-1.5`}
              >
                <div>
                  <div className="flex items-center justify-between">
                    <span className="font-bold uppercase text-[9px]">{expert.detail.name}</span>
                    <span className="text-[8px] bg-white/5 border border-white/10 px-1 py-0.1 rounded font-sans font-normal text-gray-500">
                      {expert.detail.model}
                    </span>
                  </div>
                  <p className="text-[9px] font-sans text-gray-400 leading-normal mt-1">{expert.detail.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>

      {/* TANGIBLE ARTIFACT-DRIVEN OUTRO (The Decision Report) */}
      {isCompleted && turns.length > 0 && (
        <div className="bg-[#0b0e0d] border border-emerald-500/40 rounded-2xl p-5 space-y-4 shadow-2xl animate-in fade-in">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-emerald-500/20 pb-3 gap-2">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 flex items-center justify-center">
                <FileCheck2 className="w-4 h-4" />
              </div>
              <div>
                <h4 className="text-white font-black uppercase text-xs tracking-wider">Deliberation Decision Report</h4>
                <p className="text-[9.5px] text-emerald-400 font-sans">Synthesized outcome verified by Foundation Referee</p>
              </div>
            </div>

            {/* Qualitative Assessment Indicators */}
            <div className="flex flex-wrap items-center gap-1.5 font-sans">
              <span className="text-[8.5px] bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 px-2 py-0.5 rounded font-bold uppercase">
                Alignment: High
              </span>
              <span className="text-[8.5px] bg-sky-500/10 text-sky-400 border border-sky-500/30 px-2 py-0.5 rounded font-bold uppercase">
                Evidence: Strong
              </span>
              <span className="text-[8.5px] bg-amber-500/10 text-amber-400 border border-amber-500/30 px-2 py-0.5 rounded font-bold uppercase">
                Architectural Risk: Low
              </span>
              <span className="text-[8.5px] bg-purple-500/10 text-purple-400 border border-purple-500/30 px-2 py-0.5 rounded font-bold uppercase">
                Consensus: Achieved
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3 font-sans text-xs">
            <div className="bg-[#101712] border border-emerald-500/20 p-3 rounded-xl space-y-1">
              <span className="text-[9px] text-emerald-400 font-mono font-bold uppercase block">1. Key Agreements</span>
              <p className="text-[11px] text-gray-200 leading-snug">
                Client-side Event Queue with IndexedDB local writes for zero offline latency.
              </p>
            </div>

            <div className="bg-[#101712] border border-emerald-500/20 p-3 rounded-xl space-y-1">
              <span className="text-[9px] text-sky-400 font-mono font-bold uppercase block">2. Resolved Disagreements</span>
              <p className="text-[11px] text-gray-200 leading-snug">
                Added WebWorker PDF rendering and a 10MB storage log compactor to prevent UI lag.
              </p>
            </div>

            <div className="bg-[#101712] border border-emerald-500/20 p-3 rounded-xl space-y-1">
              <span className="text-[9px] text-amber-400 font-mono font-bold uppercase block">3. Identified Risks</span>
              <p className="text-[11px] text-gray-200 leading-snug">
                Mitigated tenant data leaks using PostgreSQL Row-Level Security and SHA-256 state tokens.
              </p>
            </div>

            <div className="bg-[#101712] border border-emerald-500/20 p-3 rounded-xl space-y-1">
              <span className="text-[9px] text-[#FFD700] font-mono font-bold uppercase block">4. Final Recommendation</span>
              <p className="text-[11px] text-white font-bold leading-snug">
                Proceed with code generation under the verified zero-drift specification.
              </p>
            </div>
          </div>

          {/* Tangible Artifacts Box (Rule #1: Must Produce Artifact) */}
          <div className="bg-[#080d0a] border border-emerald-500/30 rounded-xl p-3.5 text-[11px] font-sans text-gray-300 space-y-2">
            <div className="flex items-center justify-between text-[9.5px] font-mono uppercase font-bold text-emerald-400 border-b border-emerald-500/20 pb-1.5">
              <span className="flex items-center gap-1.5">
                <BookOpen className="w-3.5 h-3.5 text-emerald-400" />
                Tangible Institutional Artifacts Generated:
              </span>
              <span>Rule #1 Enforced</span>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 text-[10px]">
              <div className="bg-emerald-950/30 border border-emerald-500/20 rounded p-2 text-emerald-300">
                <span className="font-bold block text-[#FFD700]">✓ 1 Architectural Decision Record (ADR-004)</span>
                <span className="text-[9px] text-gray-400">IndexedDB Event Queue + RLS Isolation</span>
              </div>
              <div className="bg-sky-950/30 border border-sky-500/20 rounded p-2 text-sky-300">
                <span className="font-bold block text-sky-400">✓ 2 Breakthrough Registrations</span>
                <span className="text-[9px] text-gray-400">Storage Compactor & WebWorker PDF</span>
              </div>
              <div className="bg-purple-950/30 border border-purple-500/20 rounded p-2 text-purple-300">
                <span className="font-bold block text-purple-400">✓ 1 Foundation Rule Verification</span>
                <span className="text-[9px] text-gray-400">Referee Cleared against Constitution</span>
              </div>
            </div>
          </div>

          {/* Action To Save To Knowledge Vault or Draft */}
          <div className="flex flex-col sm:flex-row items-center justify-between border-t border-emerald-500/20 pt-3 gap-3">
            <button
              onClick={() => setShowRawTranscript(!showRawTranscript)}
              className="text-[10px] text-gray-400 hover:text-white flex items-center gap-1 cursor-pointer font-mono"
            >
              {showRawTranscript ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
              <span>{showRawTranscript ? 'Hide Raw Deliberation Transcript' : 'Expand Raw Deliberation Transcript'}</span>
            </button>

            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => addLog('Deliberation decision draft saved.', 'INFO', 'SPINE')}
                className="bg-[#181818] hover:bg-[#222] border border-[#333] text-gray-300 font-bold px-3 py-2 rounded-xl text-[10px] uppercase transition cursor-pointer"
              >
                Save as Draft
              </button>

              <button
                onClick={handleAdoptPlan}
                disabled={adopted}
                className={`px-5 py-2 rounded-xl font-black uppercase text-xs transition flex items-center gap-2 cursor-pointer shrink-0 shadow-lg ${
                  adopted
                    ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/40 cursor-default'
                    : 'bg-[#FFD700] hover:bg-[#FFD700]/90 text-black'
                }`}
              >
                {adopted ? (
                  <>
                    <Check className="w-4 h-4 stroke-[3]" />
                    <span>Saved to Knowledge Vault</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4" />
                    <span>Save to Knowledge Vault</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Collaborative Steering Input (Ladder Level 2 only) */}
      {ladderLevel === 2 && isRunning && (
        <form onSubmit={handleSendSteeringInput} className="flex gap-2">
          <input
            type="text"
            value={userInput}
            onChange={(e) => setUserInput(e.target.value)}
            placeholder="Steer the deliberation in real-time (e.g. 'We must support offline photo rendering')..."
            className="flex-1 bg-[#111] border border-[#2a2a2a] focus:border-[#FFD700] rounded-xl px-4 py-2.5 text-xs text-white placeholder-gray-500 outline-none font-sans"
          />
          <button
            type="submit"
            className="bg-[#FFD700] text-black font-bold px-4 py-2.5 rounded-xl uppercase text-xs cursor-pointer flex items-center gap-1.5"
          >
            <span>Steer</span>
          </button>
        </form>
      )}

      {/* Active Deliberation Transcript Console */}
      {(isRunning || showRawTranscript || ladderLevel === 1) && (
        <div className="bg-[#0b0b0b] border border-[#1e1e1e] rounded-xl p-4 space-y-4 min-h-[200px] max-h-[350px] overflow-y-auto scrollbar-thin">
          
          {turns.length === 0 && !isRunning && (
            <div className="flex flex-col items-center justify-center text-center py-10 text-gray-500 space-y-2">
              <Users className="w-8 h-8 text-gray-600" />
              <span className="text-xs font-bold uppercase text-gray-400">Deliberation Session Ready</span>
              <p className="text-[10.5px] font-sans max-w-sm text-gray-500">
                Click "Convene Deliberation" above to start multi-expert architectural synthesis.
              </p>
            </div>
          )}

          {turns.map((turn) => {
            const isUser = turn.speakerRole === 'User';
            const isReferee = turn.speakerRole === 'Referee';

            if (isReferee) {
              return (
                <div key={turn.id} className="bg-[#151208] border border-[#FFD700]/30 rounded-xl p-3 text-[10.5px] text-[#FFD700] space-y-1">
                  <div className="flex items-center gap-1.5 font-bold uppercase text-[9px]">
                    <Shield className="w-3.5 h-3.5" />
                    <span>{turn.speakerName}</span>
                    <span className="text-gray-500 ml-auto">{turn.timestamp}</span>
                  </div>
                  <p className="font-sans text-gray-200">{turn.message}</p>
                </div>
              );
            }

            return (
              <div
                key={turn.id}
                className={`flex gap-3 ${isUser ? 'justify-end' : 'justify-start'}`}
              >
                {!isUser && (
                  <div className={`w-7 h-7 rounded-lg flex items-center justify-center font-bold text-xs shrink-0 mt-0.5 ${turn.avatarColor}`}>
                    <Users className="w-4 h-4" />
                  </div>
                )}

                <div className={`max-w-[85%] space-y-2 rounded-xl p-3.5 border ${
                  isUser
                    ? 'bg-[#101411] border-emerald-500/30 text-gray-200 rounded-tr-none'
                    : 'bg-[#121212] border-white/10 text-gray-200 rounded-tl-none'
                }`}>
                  <div className="flex items-center justify-between gap-4 text-[9px] border-b border-white/5 pb-1">
                    <div className="flex items-center gap-1.5">
                      <span className="font-bold uppercase text-white">
                        {turn.speakerName}
                      </span>
                      <span className="text-gray-500 font-sans">({turn.speakerRole})</span>
                    </div>
                    <div className="flex items-center gap-2 text-gray-500">
                      <span>{turn.timestamp}</span>
                    </div>
                  </div>

                  <p className="text-[11px] font-sans leading-relaxed text-gray-200">
                    {turn.message}
                  </p>

                  {turn.keyTakeaway && (
                    <div className="bg-black/60 border border-white/10 rounded p-2 text-[9.5px] text-[#FFD700] font-mono flex items-center gap-1.5">
                      <Zap className="w-3 h-3 text-[#FFD700] shrink-0" />
                      <span>{turn.keyTakeaway}</span>
                    </div>
                  )}
                </div>

                {isUser && (
                  <div className={`w-7 h-7 rounded-lg flex items-center justify-center font-bold text-xs shrink-0 mt-0.5 ${turn.avatarColor}`}>
                    <Users className="w-4 h-4" />
                  </div>
                )}
              </div>
            );
          })}

          {isRunning && (
            <div className="flex items-center gap-2 text-gray-400 text-xs p-3 bg-[#111] border border-[#222] rounded-xl w-fit">
              <RefreshCw className="w-3.5 h-3.5 text-[#FFD700] animate-spin" />
              <span>Deliberating decision parameters...</span>
            </div>
          )}

          <div ref={scrollRef} />
        </div>
      )}

    </div>
  );
}
